import os
from pathlib import Path

filepath = Path(__file__).resolve().parent / "workflow.md"

content = r"""# CoChem-SEED: Master Coding Specification & Workflow
**Date:** 2026-08-07
**Target:** Implementation Phase (Coding LLM Instructions)

> [!CAUTION]
> **ATTENTION CODING AGENT:** This document is your absolute blueprint. You are to write the actual Python, React, and configuration files to build the `CoChem-SEED` suite based exactly on the constraints laid out here. Deviation from this architecture is strictly prohibited.

## Phase 1: Environment & Devcontainer Scaffold
You must first completely eradicate the legacy `core_logic/` and Jupyter notebook environments. The new standard is a standalone GitHub Classroom 50 Codespace.

**Task 1.1:** Delete the legacy `core_logic/` and `notebooks/` directories.
**Task 1.2:** Create `.devcontainer/devcontainer.json`.
- It MUST use a Python + Node.js universal image.
- It MUST forward ports `3000` (Vite frontend) and `8000` (FastAPI backend).
- The repository must be configured to utilize Classroom 50 Advanced Settings to invisibly deploy the OS, Python (MACE, Thessues), and other dependencies.
- `postCreateCommand`: Must run `pip install -r backend/requirements.txt` and `npm install` in the frontend.

**Task 1.3:** Create `.devcontainer/Dockerfile`.
- It MUST natively install the `mace` and `thessues` packages for physics predictions.

## Phase 2: The Backend Physics & API Tier (FastAPI)
You will build a self-contained FastAPI backend in `backend/app/main.py`.

**Task 2.1:** Code `physics_local.py`.
- Write functions to invoke MACE-OFF24, MACE IR, and Thessues locally, replicating the standalone exactness requested for the physics engines.

**Task 2.2:** Code `api_sdbs.py` and `api_nist.py`.
- Write functions to download and parse raw `.jdx` files from the SDBS and NIST databases for experimental comparison.

**Task 2.3:** Code `socratic_llm.py`.
- Implement the intelligent grading engine with cryptographic salting (FERPA compliance).
- Set the exact system prompt: *"You are a strict Socratic Chemistry TA. You have access to the student's theoretical MACE peak and the experimental SDBS peak. If the student asks for the direct answer, deduct 10 points and ask a guiding question. If the student justifies the difference using correct chemical logic, award 20 points."*

## Phase 3: The Frontend React UI (Vite)
You will build a premium Glassmorphism UI in `frontend/`.

**Task 3.1:** Initialize the Vite React project and install `tailwindcss`, `framer-motion`, and `molstar`.
**Task 3.2:** Ensure the UI identically matches the premium interface mocked up for `CoChem-GUI`.
**Task 3.3:** Integrate Molstar for 3D coordinate rendering (using the outputs generated by MACE-OFF24).

## Phase 4: Socratic & Interactive Components
**Task 4.1:** Build interactive components for the drag-and-drop Mass-Spec puzzle and NMR symmetry timers.
**Task 4.2:** Ensure all student actions ping the FastAPI backend to log progress via the `socratic_llm` intent grading logic.

## Phase 5: Electron Fallback Wrapper (Standalone .exe)
**Task 5.1:** Create `electron_fallback/main.js`. 
- Write the Electron wrapper that invisibly spawns the Python FastAPI server as a background process and opens the React build in a standalone native desktop window.
- Ensure PyInstaller instructions are written in a `build.bat` script for compiling the final `.exe`. This allows the exact same React/FastAPI stack to be deployed offline.

### Final Verification
Once you have written all of the above code, you must execute the `.devcontainer` locally to verify that ports 3000 and 8000 successfully communicate and the MLFF engines execute flawlessly.
"""

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

import logging

logger = logging.getLogger("Generate_Seed_Workflow")
logger.info(f"Generated workflow document at {filepath}")
